import { definePatterns } from "../types.js";

export default definePatterns([
	{
		name: "eval() usage",
		regex: /\beval\s*\(/g,
		severity: "high",
		message: "eval() can execute arbitrary code and is a security risk",
		fix: "Replace eval() with safer alternatives like JSON.parse() or a proper parser",
		fileTypes: [".js", ".ts", ".jsx", ".tsx", ".mjs"],
	},
	{
		name: "child_process spawn with shell",
		regex: /spawn\s*\([^)]*shell\s*:\s*true/g,
		severity: "high",
		message: "Spawning with shell: true can lead to command injection",
		fix: "Use spawn() without shell option and pass arguments as array",
		fileTypes: [".js", ".ts"],
	},
	{
		name: "SQL template literal injection",
		regex: /`[\s\S]{0,20}(SELECT|INSERT|UPDATE|DELETE)[\s\S]{0,50}\$\{/gi,
		severity: "critical",
		message: "SQL query built with template literal is vulnerable to injection",
		fix: "Use parameterized queries with prepared statements",
		fileTypes: [".js", ".ts"],
	},
	{
		name: "SSRF via fetch",
		regex: /fetch\s*\(\s*[^"'`][^)]*\)|fetch\s*\(\s*`[^`]*\$\{/g,
		severity: "high",
		message: "Fetch with potentially user-controlled URL",
		fix: "Validate and whitelist allowed URL schemes and hosts",
		fileTypes: [".js", ".ts"],
	},
	{
		name: "Path traversal via file read",
		regex: /readFileSync\s*\([^"'`]|readFile\s*\([^"'`]|fs\.(read|write)[^(]*\([^"'`]/g,
		severity: "high",
		message: "File operation with potentially user-controlled path",
		fix: "Validate path and use path.resolve() to prevent directory traversal",
		fileTypes: [".js", ".ts"],
	},
	{
		name: "XXE via DOMParser",
		regex: /DOMParser\s*\(\s*\)|\.parseFromString\s*\(/g,
		severity: "medium",
		message: "XML parsing - ensure external entities are disabled",
		fix: "Use JSON instead of XML, or disable external entity processing",
		fileTypes: [".js", ".ts"],
	},
	{
		name: "dangerouslySetInnerHTML",
		regex: /dangerouslySetInnerHTML\s*=\s*\{/g,
		severity: "medium",
		message: "dangerouslySetInnerHTML can lead to XSS if content is not sanitized",
		fix: "Ensure content is sanitized or use a library like DOMPurify",
		fileTypes: [".js", ".jsx", ".tsx"],
	},
	{
		name: "Weak crypto algorithm",
		regex: /createHash\s*\(\s*['"]md5['"]\)|createHash\s*\(\s*['"]sha1['"]\)/gi,
		severity: "medium",
		message: "MD5 and SHA1 are weak hashing algorithms",
		fix: "Use SHA256 or stronger algorithms",
		fileTypes: [".js", ".ts"],
	},
	{
		name: "Math.random for security",
		regex: /Math\.random\s*\(\s*\)/g,
		severity: "medium",
		message: "Math.random() is not cryptographically secure",
		fix: "Use crypto.randomBytes() or crypto.getRandomValues() for security-sensitive random values",
		fileTypes: [".js", ".ts"],
	},
]);
