import { definePatterns } from '../types.js';

/**
 * Cross-language patterns that apply to multiple file types
 */
export default definePatterns([
  {
    name: 'Plaintext password comparison',
    regex: /password\s*==\s*|==\s*password|hash\s*==\s*|==\s*hash|verify_password.*==|==.*verify_password/gi,
    severity: 'critical',
    message: 'String comparison for passwords/hashes is vulnerable to timing attacks',
    fix: 'Use constant-time comparison functions like subtle::ConstantTimeEq or crypto secure_compare',
    fileTypes: ['.rs', '.py', '.js', '.ts', '.go'],
  },
  {
    name: 'Commented security middleware',
    regex: /\/\/\s*(rate.?limit|tower.?governor|throttle|brute.?force|auth.?guard|security|helmet)/gi,
    severity: 'medium',
    message: 'Security middleware appears to be commented out',
    fix: 'Uncomment and enable security middleware before deploying',
    fileTypes: ['.rs', '.js', '.ts', '.py'],
  },
  {
    name: 'exec() usage',
    regex: /\bexec\s*\(/g,
    severity: 'high',
    message: 'exec() can execute arbitrary shell commands',
    fix: 'Use parameterized commands or escape user input properly',
    fileTypes: ['.js', '.ts', '.py'],
  },
  {
    name: 'SQL concatenation',
    regex: /["'`][\s\S]{0,50}(SELECT|INSERT|UPDATE|DELETE)[\s\S]{0,50}["'`]\s*\+|\+\s*["'`][\s\S]{0,50}(SELECT|INSERT|UPDATE|DELETE)/gi,
    severity: 'critical',
    message: 'SQL string concatenation is vulnerable to SQL injection',
    fix: 'Use parameterized queries or an ORM',
  },
  {
    name: 'Base64 encoded credentials',
    regex: /base64[._-]?decode\s*\([^)]*['"]\s*[A-Za-z0-9+/=]{16,}['"]/gi,
    severity: 'high',
    message: 'Potentially hardcoded credentials encoded in base64',
    fix: 'Use environment variables or secrets management for credentials',
    fileTypes: ['.py', '.js', '.ts', '.rb', '.go', '.php'],
  },
  {
    name: 'Base64 decode for password',
    regex: /password\s*=\s*[^;]*atob\s*\(|password\s*=\s*[^;]*base64\.decode\s*\(|password\s*=\s*Buffer\.from\s*\([^,]*,\s*['"]base64['"]\)/gi,
    severity: 'critical',
    message: 'Password retrieved via base64 decode - likely hardcoded credentials',
    fix: 'Use environment variables or secrets management for credentials',
    fileTypes: ['.py', '.js', '.ts', '.rb', '.go', '.php'],
  },
  {
    name: 'Hardcoded SSH/database connection',
    regex: /(ssh|paramiko|mysql|postgres|redis)\.connect\s*\([^)]*password\s*=\s*['"]/gi,
    severity: 'critical',
    message: 'Hardcoded credentials in connection string',
    fix: 'Use environment variables or secrets management',
    fileTypes: ['.py'],
  },
  {
    name: 'Hidden admin/role field',
    regex: /type\s*=\s*["']hidden["'][^>]*(admin|role|privilege|permission|is_?admin|is_?super)/gi,
    severity: 'high',
    message: 'Hidden form field controlling access - vulnerable to tampering',
    fix: 'Never trust client-side hidden fields for authorization; validate server-side',
    fileTypes: ['.html', '.php', '.erb', '.ejs', '.jsx', '.tsx'],
  },
  {
    name: 'JWT none algorithm',
    regex: /algorithm\s*[=:]\s*["']none["']|alg["']?\s*:\s*["']none["']/gi,
    severity: 'critical',
    message: 'JWT with "none" algorithm allows signature bypass',
    fix: 'Always specify and validate a secure algorithm (RS256, ES256)',
    fileTypes: ['.py', '.js', '.ts', '.rb', '.go'],
  },
  {
    name: 'JWT weak secret',
    regex: /jwt\.(encode|sign|decode|verify)\s*\([^)]*["'](secret|password|key|123|test|dev)["']/gi,
    severity: 'high',
    message: 'JWT using weak or hardcoded secret',
    fix: 'Use strong, randomly generated secrets from environment variables',
    fileTypes: ['.py', '.js', '.ts'],
  },
  {
    name: 'Disabled SSL verification',
    regex: /rejectUnauthorized\s*:\s*false|verify\s*=\s*False|InsecureSkipVerify\s*:\s*true/g,
    severity: 'high',
    message: 'Disabled SSL verification makes connections vulnerable to MITM attacks',
    fix: 'Enable SSL verification and use proper certificates',
  },
  {
    name: 'Hardcoded localhost/127.0.0.1 in production code',
    regex: /['"]https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?['"]/g,
    severity: 'low',
    message: 'Hardcoded localhost URLs may cause issues in production',
    fix: 'Use environment variables for URLs',
  },
  {
    name: 'CORS wildcard',
    regex: /['"]Access-Control-Allow-Origin['"]\s*[,:]\s*['"]\*['"]/gi,
    severity: 'medium',
    message: 'CORS wildcard (*) allows any origin to access this resource',
    fix: 'Restrict CORS to specific trusted origins',
  },
  {
    name: 'Debug mode enabled',
    regex: /DEBUG\s*=\s*True|debug\s*:\s*true|NODE_ENV\s*[!=]==?\s*['"]development['"]/gi,
    severity: 'low',
    message: 'Debug mode may be enabled - ensure this is not deployed to production',
    fix: 'Use environment variables to control debug mode',
  },
]);
